project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Examining the Blue Acres Program and NFIP Claims in New Jersey"
  site-url: "https://musa-550-fall-2023.github.io/quarto-website-template" 
  repo-url: https://github.com/MUSA-550-Fall-2023/quarto-website-template 
  repo-actions: [source]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-Dave Drennan, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/davedrenn/
        text: "GitHub Profile"      

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-python-code-blocks.qmd 
          - analysis/2-static-images.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: minty
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




